### ISSUE TITLE
タスクランナー(Gulp)の導入

### ISSUE THREAD

**Issue by S-Yamamoto3215** [yutakawano/digsmile#5]

**Comment by S-Yamamoto3215** [comment]
- brewの導入
- anyenvの導入
- anyenvを使ってnodenvの導入
- brewを使ってyarnの導入
- yarnを使ってライブラリの導入
  - yarn add -D gulp@next gulp-sass gulp-autoprefixer gulp-plumber
- gulpfile.jsの作成

**Comment by S-Yamamoto3215** [comment]
# brewの導入

本家サイト
https://brew.sh/index_ja

ググってよしなに導入
ターミナルで'brew -v'とかしてバージョン情報出ればOK

**Comment by S-Yamamoto3215** [comment]
# anyenvの導入
`brew search anyenv`

`brew install anyenv`

`anyenv -v`

バージョン情報出ればOK

**Comment by S-Yamamoto3215** [comment]
# anyenvを使ってnodenvの導入

`anyenv install nodenv`

`nodenv install 14.17.0`

`node -v`

バージョン情報が出ればOK
ちなみにバージョンは現時点で推奨版である14.17.0

**Comment by S-Yamamoto3215** [comment]
# brewを使ってyarnの導入
`brew search yarn`

`brew install yarn`

`yarn -v`

バージョン情報でればOK

**Comment by S-Yamamoto3215** [comment]
# yarnを使ってライブラリの導入

`yarn add 〜`はプロジェクトにライブラリを追加する時のみ実行する。
パッケージの依存関係などを考慮して開発に必要なライブラリをインストールする場合は
`yarn install`でOK

`yarn install`はプロジェクトのルートにある`package.json`をもとにライブラリのインストールをする。

**Comment by S-Yamamoto3215** [comment]
gulpに実行は以下
`yarn exec gulp`

gulpfile.jsを作ったら終わり

**Comment by yutakawano** [comment]
homebrew導入完了
バージョン 3.1.12

**Comment by yutakawano** [comment]
### anyenv導入

$ brew install anyenv
$ anyenv -v
anyenv: command not found
となり、anyenvが見つからない。

**Comment by yutakawano** [comment]
### パスを通そうとしたが格納されているディレクトリが分からない

参考：https://qiita.com/soarflat/items/09be6ab9cd91d366bf71

$ echo $PATH
/usr/local/heroku/bin:/usr/local/heroku/bin:/home/ubuntu/.nvm/versions/node/v10.24.1/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3@global/bin:/home/ubuntu/.rvm/rubies/ruby-2.6.3/bin:/usr/local/heroku/bin:/usr/local/heroku/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3@global/bin:/home/ubuntu/.rvm/rubies/ruby-2.6.3/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3@global/bin:/home/ubuntu/.rvm/rubies/ruby-2.6.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/usr/local/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/usr/local/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/usr/local/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.rvm/bin

大量のパスが見つかったため下記で探す。
$ which anyenv
何の反応も無い。

$ find anyenv
find: ‘anyenv’: No such file or directory
となり、このディレクトリには無いらしい。そもそもどのディレクトリを見ているのかという疑問。

$ echo anyenv
anyenv
となるので、あるはあるらしい。
