### ISSUE TITLE
開発環境の整備

### ISSUE THREAD

**Issue by S-Yamamoto3215** [yutakawano/digsmile#7]
## ゴール
yarnを使ってscssをcssにビルドできるようにする

## やり方
必要な各種ツールのインストールはこっちにまとめた
#5 

上記を対応したら、リポジトリのルートで
`yarn exec gulp`を実行してみる。

エラー無く`Starting 'default'...`でファイル監視が始まったら成功。

**Comment by yutakawano** [comment]
### brew導入完了
バージョン 3.1.12

**Comment by yutakawano** [comment]
### anyenv導入
$ brew install anyenv
$ anyenv -v
anyenv: command not found
となり、anyenvが見つからない。

**Comment by yutakawano** [comment]
### パスを通そうとしたが格納されているディレクトリが分からない
参考：https://qiita.com/soarflat/items/09be6ab9cd91d366bf71

$ echo $PATH
/usr/local/heroku/bin:/usr/local/heroku/bin:/home/ubuntu/.nvm/versions/node/v10.24.1/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3@global/bin:/home/ubuntu/.rvm/rubies/ruby-2.6.3/bin:/usr/local/heroku/bin:/usr/local/heroku/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3@global/bin:/home/ubuntu/.rvm/rubies/ruby-2.6.3/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3/bin:/home/ubuntu/.rvm/gems/ruby-2.6.3@global/bin:/home/ubuntu/.rvm/rubies/ruby-2.6.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/usr/local/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/usr/local/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.local/bin:/home/ubuntu/bin:/usr/local/bin:/home/ubuntu/.rvm/bin:/home/ubuntu/.rvm/bin

大量のパスが見つかったため下記で探す。
$ which anyenv
何の反応も無い。

$ find anyenv
find: ‘anyenv’: No such file or directory
となり、このディレクトリには無いらしい。そもそもどのディレクトリを見ているのかという疑問。

$ echo anyenv
anyenv
となるので、あるはあるらしい。

**Comment by S-Yamamoto3215** [comment]
## 質問
(1)「パスを通す」ってどういうことか自分なりの言葉でいいので説明してください。
(2) whichコマンドは何をするコマンドですか？
(3) findコマンドは何をするコマンドですか？
(4)echoコマンドは何をするコマンドですか？

**Comment by yutakawano** [comment]
(1)「パスを通す」ってどういうことか自分なりの言葉でいいので説明してください。
→パソコンのどこかにあるプログラムを、プログラム名だけで検索し実行できるように、環境変数$PATHに、指定されたコマンドのフルパスを書き込む、という意味

(2) whichコマンドは何をするコマンドですか？
→指定されたコマンドのフルパスを探すコマンド

(3) findコマンドは何をするコマンドですか？
→ファイルやディレクトリを検索するコマンド

(4)echoコマンドは何をするコマンドですか？
→文字列や変数を表示するコマンド

**Comment by yutakawano** [comment]
### brew導入
homebrew 3.1.12
└homebrew：ユーザーがソースコードを取得し、自らビルドするパッケージ管理システム

### anyenvをgit cloneで導入
anyenv 1.1.3-2-g49e6ea5
└anyenv：rbenvやnodenvなどのenv系を複数パージョンをインストールできるツール
└clone：git clone https://〇〇 ./〇〇　などでgitのリモートリポジトリから丸々ダウンロードし、指定のディレクトリに格納できる。
※今回brewでインストール予定だったが、上手くいかなかったためcloneで導入することに

### anyenvを使ってnodenvを導入
nodenv 1.4.0+3.631d0b6
└nodenv：Node.jsをプロジェクト(フォルダ)毎にバージョンを設定することができるツール
└Node.js：JavaScriptをサーバーサイドで利用できるプログラム。Node.jsのパッケージであるgulpを利用することができる。

node -v
└v12.21.0

### brewを使ってyarnを導入
yarn 1.22.5
└yarn：Node.jsのパッケージマネージャー。npmと互換性があり、package.josnが使える。npmよりインストールが早く、自動で生成されるyarn.lockファイルに記載されたバージョンでしかインストールが行われないためセキュリティも高い。今回yarnを使い、package.jsonをもとにライブラリ(gulp)のインストールを行う。

package.json：

### yarnを使ってpackage.jsonにライブラリを追加
yarn add -D gulp@next gulp-sass gulp-autoprefixer gulp-plumber
└gulp-sass：SCSSをCSSにコンパイルする
└gulp-autoprefixer：CSSにベンダープレフィックスをつける
└gulp-plumber：実行中のタスク強制停止を防止する

### npmを使ってgulpをグローバルインストール
gulp
└CLI version: 2.3.0
└Local version: 4.0.2

yarnを使うためにbrewを導入したが、混乱してnpmでインストール。
└グローバルインストール：ユーザーのマシン上のどこからでもgulpが使えるようになる。
└ローカルインストール：そのプロジェクト内のみでgulpが使えるようになる。
└グローバルインストールしたgulpを実行することでローカルインストールしたgulpを実行することになる。

### ヤマもんさん設定のリモートリポジトリ(gulpfile.jsなど)をローカルにpull

**Comment by yutakawano** [comment]
### yarn exec gulpの実行
結果が下記。

```
yarn exec v1.22.5
warning package.json: No license field
[06:04:41] No gulpfile found
error Command failed.
Exit code: 1
Command: gulp
Arguments: 
Directory: /home/ubuntu/environment/digsmile
Output:
info Visit https://yarnpkg.com/en/docs/cli/exec for documentation about this command.
```
下記のエラーが発生、という認識。
エラー1：package.jsonにライセンスが無い
エラー2：gulpfileが見つからない

**Comment by yutakawano** [comment]
### シェルを再起動して再度gulpを実行
結果が下記

```
yarn exec v1.22.5
warning package.json: No license field
[06:24:37] Using gulpfile ~/environment/digsmile/gulpfile.js
[06:24:37] Task never defined: default
[06:24:37] To list available tasks, try running: gulp --tasks
error Command failed.
Exit code: 1
Command: gulp
Arguments: 
Directory: /home/ubuntu/environment/digsmile
Output:

info Visit https://yarnpkg.com/en/docs/cli/exec for documentation about this command.
```

エラー1：package.jsonにライセンスが無い
エラー2：タスクが定義されていない

**Comment by yutakawano** [comment]
### nodenv経由でnode.jsを下記でインストール
nodenv install 14.17.0

実行結果↓
nodenv 1.4.0+3.631d0b6

**Comment by yutakawano** [comment]
### yarn installでエラー発生
ヤマもんさんが設定してくれたリモートリポジトリ(gulpfile.jsなど)を河野のローカルにpull。

その後yarn installを実行したが下記エラーが発生。
```
error An unexpected error occurred: "/home/ubuntu/environment/digsmile/package.json: Unexpected token < in JSON at position 112".
info If you think this is a bug, please open a bug report with the information provided in "/home/ubuntu/environment/digsmile/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
### エラー内容をざっくり和訳
`jsonの位置112に予期しないエラーが発生しています。yarnのドキュメントを参考にyarn-error.logを見てください。`

### yarn-error.logの内容
```
SyntaxError: /home/ubuntu/environment/digsmile/package.json: Unexpected token < in JSON at position 112
      at JSON.parse (<anonymous>)
      at /usr/share/yarn/lib/cli.js:1625:59
      at Generator.next (<anonymous>)
      at step (/usr/share/yarn/lib/cli.js:310:30)
      at /usr/share/yarn/lib/cli.js:321:13
```
package.jsonで構文エラーが発生している可能性。

gitのpackage.jsonは下記
```
{ 
 "devDependencies": {    
"gulp": "^4.0.2", 
   "gulp-autoprefixer": "^8.0.0", 
   "gulp-plumber": "^1.2.1", 
   "gulp-sass": "^4.1.0", 
   "gulp-sourcemaps": "^3.0.0" 
 }
}
```
cloud9のpackage.jsonの中身は下記
```
{
  "devDependencies": {
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^8.0.0",
    "gulp-plumber": "^1.2.1",
<<<<<<< HEAD
    "gulp-sass": "^4.1.0"
=======
    "gulp-sass": "^4.1.0",
    "gulp-sourcemaps": "^3.0.0"
>>>>>>> d8df90a304cefbfa4c0426f4cbeafbbcd3491f82
  }
}
```
gitの記述と異なるので、cloud9のpackage.jsonにgitのコードをコピペしたら上手くいきそうな気がする。

**Comment by yutakawano** [comment]
yarn install v1.22.5
error An unexpected error occurred: "/home/ubuntu/environment/digsmile/package.json: Unexpected token < in JSON at position 112".
info If you think this is a bug, please open a bug report with the information provided in "/home/ubuntu/environment/digsmile/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by S-Yamamoto3215** [comment]
## エラーの内容について
> package.jsonで構文エラーが発生している可能性。

エラーの内容はそのとおりです。

## 修正方法に関する意見
> gitの記述と異なるので、cloud9のpackage.jsonにgitのコードをコピペしたら上手くいきそうな気がする。

確かにこれで直るのですが、その直し方は本質絵的ではなく
また、今回のエラーの原因が何だったのかわからないままになってしまいます。
そのへんも理解した上で次へ進んだほうが良いので遠回りですが一つずつやっていきます。

---
## 新しい質問

- 構文エラーはどの部分ことですか？
- 今回のコンフリクトの原因は何でしょうか？
  - なぜpackage.jsonがコンフリクトしたのか

### ヒント
- package.jsを編集した覚えがないのに編集されてしまっているのにはあることをしたのが原因です。
  - yarnについて理解しましょう
- yarn以外にも原因があります。

**Comment by yutakawano** [comment]
少し回答させていただきます。

> 構文エラーはどの部分ことですか？

下記package.json内の
```
{
  "devDependencies": {
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^8.0.0",
    "gulp-plumber": "^1.2.1",
<<<<<<< HEAD
    "gulp-sass": "^4.1.0"
=======
    "gulp-sass": "^4.1.0",
    "gulp-sourcemaps": "^3.0.0"
>>>>>>> d8df90a304cefbfa4c0426f4cbeafbbcd3491f82
  }
}
```
下記で構文エラーが発生。
```
<<<<<<< HEAD
    "gulp-sass": "^4.1.0"
=======
    "gulp-sass": "^4.1.0",
    "gulp-sourcemaps": "^3.0.0"
>>>>>>> d8df90a304cefbfa4c0426f4cbeafbbcd3491f82
```

> 今回のコンフリクトの原因は何でしょうか？

コンフリクトの原因は、package.jsonのローカルリポジトリとリモートリポジトリに差が出てしまったため。

> なぜpackage.jsonがコンフリクトしたのか

package.jsonを編集した覚えがないのに編集されてしまったから。
そこでgit statusの実行。
package.jsonの他にもyarn.lockがマージされていないことが確認できたため、yarn.lockが主の原因と仮定。

yarn.lockを調査中。。

**Comment by yutakawano** [comment]
yarn init：package.jsonが追加される
package.json：タスクランナーなどのアプリケーション情報、バージョン範囲が記録されているファイル

yarn install：package.jsonを元に必要なパッケージをインストールし、yarn.lockを生成(更新)する。
yarn.lock；プロジェクトに依存する正確なバージョンの情報が記録されているファイル

**Comment by S-Yamamoto3215** [comment]
あっています👍

initは他のライブラリやプログラミングでは一般的に「初期化」を意味する「initialized」の略なので覚えておくと良いです。

ではどういった場合にpackage.jsonやyarn.lockが編集されると思いますか？

**Comment by S-Yamamoto3215** [comment]
テストのコメントです。slack通知されるかな〜

**Comment by yutakawano** [comment]
yarn add <パッケージ>を実行した場合に、新しいパッケージがpackage.jsonに追加され、yarn.lockが更新されます。

**Comment by S-Yamamoto3215** [comment]
つまり
nodeバージョンの違う状態でyarn add したら最新の`package.json`と`yarn.lock`で変更差分が出た。
↑これは理解できましたか？

**Comment by yutakawano** [comment]
7割ほど理解できたような気がします。
確か14.17.0ではないnodeのバージョンでyarn add gulp~を実行した記憶があるので、その時のnodeのバージョンに適したpackage.jsonとyarn.lockが生成されてしまい、今回node14.17.0をpullしていることでコンフリクトが起きた
ということでしょうか？

**Comment by yutakawano** [comment]
## gitコマンドを使って、まっさらにする
node12.21.0でyarn addを実行後にコミット。
その後、node14.17.0のファイル等をgit pullしたことでコンフリクト発生。
なので、直前のコミットを取り消す。

### 直前のコミットを消去
git reset --hard HEAD^

### nodeのバージョンを14.17.0に切り替え
node local 14.17.0
node -v
v14.17.0
↑現在地です。

### yarn install？？

**Comment by yutakawano** [comment]
最後に「開発環境の整備フロー」と「整備する中で詰まった点」をまとめます。

## ゴール
yarnを使ってscssをcssにビルドできるようにする・・・scssをcssにコンパイルするためのgulp導入と開発環境の整備

## 開発環境の整備フロー

1. homebrewをインストールした
2. anyenvをインストールした(homebrewではエラーが発生したため、cloneコマンドにより、githubのソースからインストール)
3. anyenvを使ってnodenvをインストールし、nodenvを使ってnode.jsをインストールした
4. npmを使ってyarnをインストールした(brewを使うはずだったが、当時混乱しておりnpmでインストールした)
5. ローカルの環境が整ったので、リモートリポジトリをローカルリポジトリにダウンロードした
6. yarnを使ってパッケージの依存関係をインストールした
※package.json(今回はgulpのコードをすでに書いてくれいていた)を元にインストールされる
7. nodeのバージョンが14.17.0であること、Gulpが実行できることを確認できた

## 整備する中で詰まった点

1. パスの通し方
2. githubの基本的な概念

### 1.パスの通し方
anyenv導入の際にcloneコマンドでgithubのソースからanyenvをインストールした。
anyenvのバージョンを確認すると、コマンドが無い(anyenv: command not found)と返された。
この状況からしばらく抜けられ無かったが「パスを通す」で解決することが判明。
※パスを通すとは、、PC上のどこかにあるプログラムをプログラム名を実行するだけでプログラムが実行されるように、環境変数$PATHにフルパスを書き込むこと。
下記のexportコマンドでパスを通した。
```
echo 'export PATH="$HOME/.anyenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(anyenv init -)"' >> ~/.bash_profile
```
anyenvという名前だけでanyenvが実行できるように、.bash_profileに環境変数$PATHを追加し、evalコマンドでターミナルを開いた際に都度初期化が実行されるようにした。

### 2.githubの基本的な概念
ステージング、ローカルリポジトリ、リモートリポジトリという3段階の構造、addとcommitとpushコマンドについてもあまり理解しておらず、リモートリポジトリをローカルリポジトリにダウンロードした際のエラーに理解が及ばない状況が続いた。

環境構築後、リモートをローカルにダウンロード、その後yarn installした際のエラー内容が下記。
```
error An unexpected error occurred: "/home/ubuntu/environment/digsmile/package.json: Unexpected token < in JSON at position 112".
info If you think this is a bug, please open a bug report with the information provided in "/home/ubuntu/environment/digsmile/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
この時、ブランチ名が(master|MERGING)となっていたため、コンフリクトしていることが判明。
gitのコミットログを確認したところ、githubにpushしていない最新のコミットがあったので削除した。
最新のコミットがAdd page-contact(コミット：nodeのバージョン指定, .gitignoreの追加の直前)であることを確認できたので、再度リモートをローカルにダウンロードした。
その際、下記エラーが発生したので、.node-version、package.jsonを削除した。
```
error: The following untracked working tree files would be overwritten by merge:
        .node-version
        package.json
Please move or remove them before you merge.
```
この時点でgithubと差分の無い状態となったので、その後は問題なくリモートをローカルにダウンロードすることができた。

**Comment by yutakawano** [comment]
### PC上に開発環境が整備された状態
brewやanyenv、yarnなどは現在PC上にインストールされている状態なので、新規リポジトリを作成した場合も利用できる。

### .gitignore
.gitignoreにファイル名を記述することで、git監視から除外する
除外する理由：重い、そもそも必要ない
そもそも必要ない理由：yarn(npm)でパッケージをインストールすると、仮置き場としてnode_modulesにダウンロードされる。
ただ、パッケージのバージョン管理はルートディレクトリにあるpackage.jsonで行うため、git監視から除外して問題ない。

### localコマンドでバージョンを合わせる
node.jsの例

1. プロジェクトで使用するnodeのバージョンを確認する
2. すでにインストールされているバージョンを確認する(nodenv versions)
3. プロジェクトで使用するバージョンがインストールされていない場合は適宜インストールする
4. localコマンドでnodeのバージョンを合わせる(nodenv local 14.17.0)
