### ISSUE TITLE
SCSSをGulp管理化に移動して整理

### ISSUE THREAD

**Issue by S-Yamamoto3215** [yutakawano/digsmile#8]
## ゴール

現在、`./css`直下で管理されているscssファイルをGulpの監視下である`./src/scss`以下に移動。
移動後もコンパイルしたcssでページを表示しても変わらず、ページ崩れしない。

## やり方
- `./css`以下のscssファイルのみを`./src/scss`以下に移動
- 移動後`./css`以下に残っている各種ファイルはすべて消す
- Gulpを使って移動させたscssをcssにコンパイル
- ページを確認して崩れてなければOK
- CSSディレクトリ以下のファイルやフォルダをgit監視から除外する

**Comment by yutakawano** [comment]
1. ブランチを作成する
2. 「やり方」それぞれのタスクでコミットする
3. 全部終わったらプルリクする

**Comment by S-Yamamoto3215** [comment]
プルリクは問題ないことを確認してマージしたので
今回学んだことやつまずいた点などを本issueに整理してcloseしてください🙋‍♂️

**Comment by yutakawano** [comment]
### 今回学んだこと
scssをcssにコンパイルするためにgulpを使用。
その際、cssフォルダに作成されるcssファイルはgit監視する必要がないので、.gitignoreにcss/*.cssを記述することでcssフォルダ内のcssファイルだけをgit監視から除外。
また、cssフォルダは最初は空の状態であるため、cssフォルダに.gitkeepを作成することでaddする。

### つまづいた点
.gitkeepの使い方が良くわからず、さらにgit statusやgit logで現状を把握しながら作業ができていないかった。

本来gitでは空のディレクトリをaddできないが、.gitkeepを作成することで可能になる。
今回で言えば、空のcssフォルダをaddするためにcssフォルダに.gitkeepを作成する必要があった。
scssフォルダも同様で、元々は空ディレクトリであったため.gitkeepを作成することでaddしていた。
現在はscssフォルダ内にはstyle.scssが存在するので.gitkeepは削除している。
